baseurl = "http://www.krishicks.com"
languageCode = "en-us"
title = "krishicks.com"
theme = "hyde-x"

[author]
  name = "Kris Hicks"

[params]
github = "https://www.github.com/krishicks"
twitter = "https://www.twitter.com/krishicks"
googleAnalytics = "UA-38009560-1"
flickr = "http://www.flickr.com/krishicks"
gravatarHash = "fce785f273a2a0cf8a3a921e4d01d048"
tagline = "Independent Software Engineer<br>krishicks@fastmail.com"

[[menu.main]]
url = "/about"
name = "About"
